#!/usr/bin/env bash
# 扫 plugins/*/go.mod 生成 builtin 插件接线,新增/删除插件后跑一次即可:
#   1) cli/.../internal/plugin/builtin/imports_gen.go  blank-import 触发自注册
#   2) cli go.mod 的 require + replace
# 插件包自身经 init() 里 sdk.RegisterBuiltin(manifest, Activate) 完成注册,
# 宿主代码零手改。
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
CLI="$ROOT/cli/ttmux-cli-go"
GEN="$CLI/internal/plugin/builtin/imports_gen.go"

mods=()
dirs=()
for gomod in "$ROOT"/plugins/*/go.mod; do
  [ -f "$gomod" ] || continue
  mod=$(sed -n 's/^module //p' "$gomod" | head -1)
  [ -n "$mod" ] || continue
  mods+=("$mod")
  dirs+=("$(basename "$(dirname "$gomod")")")
done

{
  echo "// Code generated by scripts/dev/gen-builtin-plugins.sh; DO NOT EDIT."
  echo "// blank-import 触发各插件包 init() 里的 sdk.RegisterBuiltin 自注册。"
  echo "package builtin"
  echo
  echo "import ("
  for mod in "${mods[@]}"; do
    echo "	_ \"$mod\""
  done
  echo ")"
} > "$GEN"

cd "$CLI"
for i in "${!mods[@]}"; do
  go mod edit -require="${mods[$i]}@v0.0.0" -replace="${mods[$i]}=../../plugins/${dirs[$i]}"
done
gofmt -w "$GEN"

echo "generated: ${GEN#$ROOT/}"
echo "plugins:   ${mods[*]}"
